// <auto-generated />
using System;
using Epsid19.ORM;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Epsid19.Migrations
{
    [DbContext(typeof(Contexte))]
    partial class ContexteModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Epsid19.Injections", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateInjection")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateRappel")
                        .HasColumnType("TEXT");

                    b.Property<string>("Marque")
                        .HasColumnType("TEXT");

                    b.Property<string>("NumLot")
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeVaccin")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Injections");
                });

            modelBuilder.Entity("Epsid19.InjectionsPersonnes", b =>
                {
                    b.Property<int>("InjectionsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonnesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("InjectionsId", "PersonnesId");

                    b.HasIndex("PersonnesId");

                    b.ToTable("InjectionsPersonnes");
                });

            modelBuilder.Entity("Epsid19.Personnes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenom")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sexe")
                        .HasColumnType("TEXT");

                    b.Property<string>("TypePersonne")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Personnes");
                });

            modelBuilder.Entity("Epsid19.InjectionsPersonnes", b =>
                {
                    b.HasOne("Epsid19.Injections", "Injections")
                        .WithMany("InjectionsPersonnes")
                        .HasForeignKey("InjectionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Epsid19.Personnes", "Personnes")
                        .WithMany("InjectionsPersonnes")
                        .HasForeignKey("PersonnesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Injections");

                    b.Navigation("Personnes");
                });

            modelBuilder.Entity("Epsid19.Injections", b =>
                {
                    b.Navigation("InjectionsPersonnes");
                });

            modelBuilder.Entity("Epsid19.Personnes", b =>
                {
                    b.Navigation("InjectionsPersonnes");
                });
#pragma warning restore 612, 618
        }
    }
}
